### ISSUE TITLE
A proxy should call Container::get() instead of creating a new instance itself

### ISSUE THREAD

**Issue by HappyRay** [PHP-DI/PHP-DI#291] opened 2015-08-12 23:21 UTC
Here is an example.

Class Foo's constructor requires a value that is not available until a method A is called.

A creates an instance of Foo
calls \DI\Container::set to register this instance.
Later in the method A, Foo->method(...) is called in directly.

If I make Foo lazy loaded, I still get an exception that Foo can't be instantiated because it is missing a dependency that can't be resolved.

However if I make the classes that depend on Foo lazy loaded, it works. It appears that the proxy will correctly look up Foo in the container in this case.

It's more intuitive and convenient to me to make Foo lazy loaded in this situation. There may be multiple classes that depend on Foo. Is it possible?

Did I miss something?

**Comment by mnapoli** [comment] 2015-08-13 07:53
Hi! Could you write the example as code :)? I'm having trouble understanding where the problem is.

**Comment by HappyRay** [comment] 2015-08-13 14:08
Sure.

This class [OutputNameGetter](https://github.com/box/TestScribe/blob/Refactor_Configuration_Initialization/src/Config/OutputTestNameGetter.php) depends on the [Output](https://github.com/box/TestScribe/blob/Refactor_Configuration_Initialization/src/Output.php) class. 

The Output class depends on the OutputInterface which is provided by the Symfony framework at runtime. The OutputNameGetter is indirectly needed by the [EngineStarter](https://github.com/box/TestScribe/blob/Refactor_Configuration_Initialization/src/EngineStarter.php) class which is the place where Output is created and registered to the container via a container->set call. 

At first I tried to make Output class lazy loaded by setting @Injectable(lazy=true). It didn't work. I still got the exception that OutputInterface can't be resolved.

Then I set @Injectable(lazy=true) on OutputNameGetter and the code worked.

I wonder if there is a better alternative.

Thanks

**Comment by mnapoli** [comment] 2015-08-13 14:35
> At first I tried to make Output class lazy loaded by setting @Injectable(lazy=true).

Since [you create Output directly](https://github.com/box/TestScribe/blob/Refactor_Configuration_Initialization/src/EngineStarter.php#L75-L76) without going through the container, I don't see how it could have worked.

**Comment by mnapoli** [comment] 2015-08-13 14:39
All in all, I highly advise you to configure the container before starting your app. Adding entries dynamically makes everything a nightmare because of what you are experiencing (and regardless of the container that you use) => you always run the risk of asking for a dependency that hasn't been defined yet.

I'll close because it's not an issue (to keep the issue tracker clean), but feel free to continue the discussion.

**Comment by HappyRay** [comment] 2015-08-13 17:10
Thanks for the information and recommendation.

This code was written when I was learning how Php-DI framework is supposed to be used. 
I realized just now that I can just register the OutputInterface which is provided by the Symfony framework at runtime as early as I have this information. It does simplify the program logic.
See my change [here](https://github.com/box/TestScribe/commit/8d4ffae3d09f252bc202765036929cf9bf79f4a6)

Is it consistent with your suggestion "I highly advise you to configure the container before starting your app."?

===

"Adding entries dynamically makes everything a nightmare because of what you are experiencing (and regardless of the container that you use) => you always run the risk of asking for a dependency that hasn't been defined yet."

This is a challenge I faced and wanted to learn more about the strategy you would recommend. 
Even with this change above, I am adding the OutputInterface entry dynamically. I am not sure what a better alternative would be at this time. 

Am I moving in the right direction?

**Comment by mnapoli** [comment] 2015-08-13 17:29
> This is a challenge I faced and wanted to learn more about the strategy you would recommend. 
Even with this change above, I am adding the OutputInterface entry dynamically. I am not sure what a better alternative would be at this time.

The root of the problem here is a tough one. The solution I would recommend can require a little bit of effort, but it's to make everything stored in the container **stateless**.

Have a look at this article: [Stateless services](https://igor.io/2013/03/31/stateless-services.html).

What this means is that any object that contains state about a current request/command/… (like an Output, an HTTP Request object, or Response) shouldn't be stored in the container as they are stateful. Stateless stuff can be statically configured in a DI config file. Things that are not stateless need to be added to the container dynamically, and sometimes they can change over time.

The downside of this is that you have to pass the Output (or Request, Response, …) around. Symfony solved this for the request by adding a `RequestStack` class: http://symfony.com/blog/new-in-symfony-2-4-the-request-stack maybe that's an idea.

This is just a recommendation though, sometimes you have to adapt and go with the easiest solution.

**Comment by HappyRay** [comment] 2015-08-13 20:50
Thanks. I read both articles you referenced.

If I understand the article correctly, my use case is slightly different. In my case, the output object and the other config object I registered explicitly with the container are immutable. To mitigate this challenge, I tried to limit such a usage to the minimum and use stateless services as much as I can. And I register them as early as possible. 

I haven't looked at the RequestStack class implementation. I assume the framework still has to manage the state somehow. In my case, I have to do it myself by registering two values with the container using the set API. 

The second place where I use the set call is [here](https://github.com/box/TestScribe/blob/master/src/EngineStarter.php). The code calculates some configuration values and registers the object with the container. 

It's not perfect solution. But it is a tradeoff I made compared to the alternative you suggested i.e. pass these values via method parameters around. 

If there is a better alternative that I missed, I'd be very interested in knowing.

**Comment by HappyRay** [comment] 2015-08-13 20:58
The original intent of this issue I think is still valid. Let me try to explain better this time.

When a class is loaded lazily, a proxy object is created first. When a method is called on the proxy object, the proxy object will attempt to create a real instance of the class and invoke the corresponding method. 

In my earlier example, the singleton of the class is registered via the container->set call after the proxy object is created. When a method is called on the proxy object, it seems that the proxy will not look up to see if an instance has been registered and will try to instantiate a new one. I wonder what the rationale behind this design is.

**Comment by mnapoli** [comment] 2015-08-14 10:42
> When a method is called on the proxy object, it seems that the proxy will not look up to see if an instance has been registered and will try to instantiate a new one.

Ah ok I see what you mean now! Sorry it took me so much time ;)

I will be reopening that as a bug thank you!

**Comment by HappyRay** [comment] 2015-08-14 14:30
Great. Thanks

**Comment by mnapoli** [comment] 2015-09-01 12:19
I have worked on reproducing it and added some more tests to cover lazy injection/proxies.

It turns out the bug I thought existed didn't exist. I read again your report and, if I understood better this time, the problem is that proxies do not take into account modifications that happened *after* they were created (e.g. create proxy, then register entry, then use proxy). I think it's correct and this shouldn't be changed. Proxies are not meant to be used for that IMO, i.e. they shouldn't be used for dynamic configurations. They should be resolved with what was configured when they were created.

**Closed by mnapoli** 2015-09-01 12:19 UTC
Labels: bug

**Comment by HappyRay** [comment] 2015-09-01 18:31
Thanks for the update.

"if I understood better this time, the problem is that proxies do not take into account modifications that happened after they were created (e.g. create proxy, then register entry, then use proxy)"
Yes, this is my understanding as well.

"I think it's correct and this shouldn't be changed. Proxies are not meant to be used for that IMO, i.e. they shouldn't be used for dynamic configurations. They should be resolved with what was configured when they were created."
What's the benefit of this approach? And what's the downside if the proxy is made to recognize configuration changes after it is created?

In my use case, I use lazy loading/proxy because one of the dependencies is not initialized yet when the proxy is created. When the proxy is used, the dependency is initialized. In this sense, the current implementation of lazy loading is recognizing the configuration changes already. What did I miss?

**Comment by mnapoli** [comment] 2015-09-01 21:17
The thing is that it's not really a feature as of today. The container is not meant to be used with dynamic configuration. Some parts work (most parts work actually), but committing to making it a feature and supporting it everywhere would be (probably) a lot of work and would definitely affect/complicate the whole project and future features/performances.

I believe in making tools very good for specific use cases. Trying to support many different use cases can sometimes kill a project. I would like PHP-DI to be more and more performant and reliable for building complex applications. Dynamic configuration isn't especially something I'm after, a lot of other containers do that very well. That whole idea means sometimes limiting some features (e.g. this one). I'm tending more and more to optimize for use cases with static configuration (PHP-DI 5 was an evolution in that direction, e.g. with the cache). Of course keeping it easy to kick of a RAD project with PHP-DI is important and will stay there, but I don't plan on expanding much on that side unless it's very easy.

**Comment by mnapoli** [comment] 2015-09-01 21:36
For example ZF is discussing going the same direction with immutable container once created: https://github.com/zendframework/zend-servicemanager/pull/8#discussion_r38474614

**Comment by HappyRay** [comment] 2015-09-01 23:58
I don't know PHP-DI's internal implementation well enough to appreciate the cost of supporting such dynamic configurations. 

I may have missed something. But I thought lazy loading was designed for the use case I have. I guess I was wrong.

Right now, I have a workaround as I described earlier.  Do you plan to change the behavior I am relying on any time soon? 

===

As discussed earlier, I found it a less attractive option to pass dynamic config information around via method parameters. For complex applications, I suspect this use case may be a common use case. I would love to know a better alternative.

**Comment by mnapoli** [comment] 2015-09-02 07:12
For complex applications I always go with a static configuration. It's not possible to optimize with dynamic configuration. For example Symfony compiles its container, it's impossible to change its configuration (or even register new entries) after it is compiled.

In PHP-DI the dynamic side will stay because it's important to be able to start a project quickly without having to worry about caches, optimizations and stuff.

> I thought lazy loading was designed for the use case I have

The use case is to avoid *the cost* of instantiating some objects by having them load lazily. E.g. imagine you have a poorly designed DB class (or Redis, etc…) that connects to the DB in the constructor. This DB class might be injected in some controllers, event listeners, … but not always used. Even though you don't use the DB on every request, it will connect to the DB server every time which is a waste. Injecting a proxy makes that happen only when actually used.

**Comment by HappyRay** [comment] 2015-09-02 16:48
Thanks for the explanation. I respect your decision.

I am in favor of static configuration too and I do that in my code when I can. To be clear, I am not asking for the dynamic part to be optimized. It's my experience and expectation that the special case of dynamic config handling is something that many developers would encounter. It doesn't necessarily mean that your container has to support it. 

It's great that I can continue using the lazy loading for my purpose for now. If it changes, I can switch to another less desirable workaround i.e. set and get the config from a statically configured component. 

Yes, I understood the performance optimization use case of the lazy loading feature. It wasn't clear to me that was the ONLY supported use case.
