### ISSUE TITLE
Inject class by annotation in parent class

### ISSUE THREAD

**Issue by szarik88** [PHP-DI/PHP-DI#274] opened 2015-06-22 08:22 UTC
I noticed a problem with dependency injection by annotation, when injection is in parent class.
To illustrate:

```php
class MyClass {
    /**
     * @Inject
     * @var Children
     */
    protected $serviceMyClass;

    public function test() {
        $this->serviceMyClass->checkMethods();
    }
}
```

and children with parent:

```php
class Parent {
    /**
     * @Inject
     * @var ServiceParent
     */
    protected $serviceParent;
}

class Children extends Parent {
    /**
     * @Inject
     * @var ServiceChildren
     */
    protected $serviceChildren;

    public function checkMethods() {
        var_dump($this->serviceChildren); // /ServiceChildren
        var_dump($this->serviceParent); // NULL (should be object /ServiceParent)
    }
}
```

Let's assume that both `ServiceParent` and `ServiceChildren` exist and are achievable.

`serviceParent` is not injected.
This issue does not occur in 4.* version.

For injection by constructor, it looks ok:

```php
class Parent {
    /**
     * @var ServiceParent
     */
    protected $serviceParent;

    public function __construct(ServiceParent $serviceParent) {
        $this->serviceParent = $serviceParent;
    }
}

**Comment by mnapoli** [comment] 2015-06-22 08:48
Hi, thanks for the report. Are you sure it works with 4.*? Is the parent property private, protected or public?

There is #257 that is very similar, but it's only for private properties, and it is both in 4.* and 5.0.

**Comment by szarik88** [comment] 2015-06-22 09:01
:) Thanks for quick response.

I'm sure, I have a running project based on `PHP-DI 4.4.7` and the same code is injected without any problems. This issue occurred after update to 5.0.0

**Comment by mnapoli** [comment] 2015-06-22 09:56
Ok, then is it a private, protected or public property?

**Comment by szarik88** [comment] 2015-06-22 10:00
My mistake I forgot to add. All of them are protected.

**Comment by mnapoli** [comment] 2015-06-22 10:10
OK thanks I'll schedule it for next release. What is weird is that there is a test for this, but maybe it only tests for public methods.

**Comment by mnapoli** [comment] 2015-09-01 12:34
It's actually a duplicate of #257, closing.

**Closed by mnapoli** 2015-09-01 12:34 UTC
Labels: bug
