### ISSUE TITLE
Impossible to call positional arguments?

### ISSUE THREAD

**Issue by rafaelbeckel** [PHP-DI/PHP-DI#584] opened 2018-03-15 22:40 UTC
I'm trying to build an object by using a generic factory that does not know the name of created object's constructor arguments. Something like this:

~~~php
public function build(string $className, ...$arguments)
{
    $container->make($className, $arguments);
}
~~~

It can receive varying optional arguments, and the created object also expects it.

I know I can make objects by calling named arguments, like this:
~~~php
$container->make(MyClass::class, [ 'arg1' => $foo, 'arg2' => $bar ]);
~~~

I expected that the container could build objects with positional arguments too, but it throws an `Entry "MyClass" cannot be resolved: Parameter $arg1 of __construct() has no value defined or guessable Full definition` error. 

Is there a way to do this using only the definitions? (I don't want to redesign the factory)

Something like:
~~~
[
    MyClassInterface::class => DI\create()->constructor(
            'foo' => getPositionalArg[0], 'bar' => getPositionalArg[1]
    ),
]
~~~

**Comment by rafaelbeckel** [comment] 2018-03-16 04:29
Looking at implementation's code, it seems it's not possible to use positional arguments with PHP-DI. The code calls a `foreach($something as $key => $value)`, so I ended up creating child factories to handle named arguments.

Maybe I'm missing something. Is it possible to use positional arguments by calling some other method?

**Comment by Greg0** [comment] 2018-06-20 12:50
I have same issue. Is available some solution for that?

**Comment by rafaelbeckel** [comment] 2018-06-20 14:30
@Greg0 it’s not possible. You need to create child factories to bulis specialized objects directly, or redesign your class’ construtor signature.

**Comment by mnapoli** [comment] 2018-06-30 16:16
Thank you for the report, closing this because this is a duplicate of #594

**Closed by mnapoli** 2018-06-30 16:16 UTC
Labels: duplicate
